version beta

diff --git a/bin/variables-env b/bin/variables-env
--- a/bin/variables-env
+++ b/bin/variables-env
@@ -4,18 +4,17 @@ function message() {
     local signal color
     local RESETC="\033[0m\e[0m"
     case "$1" in
-        "-title")       color="\033[0;37m\033[1m"; signal="[$]"; shift; echo -e "\n${color}${signal} $*${RESETC}";;
-        "-subtitle")    color="\033[0;35m\033[1m"; signal="[*]"; shift; echo -e "\n\t${color}${signal} $*${RESETC}";;
-        "-approval")    color="\033[38;5;51m\033[1m"; signal="[?]"; shift; echo -e "\n${color}${signal} $*${RESETC}";;
-        "-success")     color="\033[0;32m\033[1m"; signal="[+]"; shift; echo -e "\t${color}${signal} $*${RESETC}";;
-        "-warning")     color="\033[0;33m\033[1m"; signal="[&]"; shift; echo -e "\t${color}${signal} $*${RESETC}";;
-        "-error")       color="\033[0;31m\033[1m"; signal="[-]"; shift; echo -e "\t${color}${signal} $*${RESETC}";;
-        "-cancel")      color="\033[0;34m\033[1m"; signal="[!]"; shift; echo -e "\n${color}${signal} $*${RESETC}\n";;
-        *)              color="$RESETC"; signal=""; shift; echo -e "${color}${signal} $*${RESETC}";;
+        "-title")       color="\033[0;37m\033[1m";      signal="[$]"; shift; echo -e "\n${color}${signal} $*${RESETC}";;
+        "-subtitle")    color="\033[0;35m\033[1m";      signal="[*]"; shift; echo -e "\n${color}${signal} $*${RESETC}";;
+        "-approval")    color="\033[38;5;51m\033[1m";   signal="[?]"; shift; echo -e "\n${color}${signal} $*${RESETC}";;
+        "-success")     color="\033[0;32m\033[1m";      signal="[+]"; shift; echo -e "\t${color}${signal} $*${RESETC}";;
+        "-warning")     color="\033[0;33m\033[1m";      signal="[&]"; shift; echo -e "\t${color}${signal} $*${RESETC}";;
+        "-error")       color="\033[0;31m\033[1m";      signal="[-]"; shift; echo -e "\t${color}${signal} $*${RESETC}";;
+        "-cancel")      color="\033[0;34m\033[1m";      signal="[!]"; shift; echo -e "\n${color}${signal} $*${RESETC}";;
+        *)              color="$RESETC";                signal=""; shift; echo -e "${color}${signal} $*${RESETC}";;
     esac
 }
 
-# Función para añadir o actualizar una variable en el archivo de entorno
 function add_or_update_variable() {
     local VAR_NAME="$1"
     local VAR_VALUE="$2"
@@ -32,12 +31,6 @@ function add_or_update_variable() {
 # Archivo de entorno (puedes cambiarlo para pruebas)
 ENV_FILE="/etc/environment"
 
-# Verifica que grep y sudo existan en el sistema
-if ! command -v grep &> /dev/null || ! command -v sudo &> /dev/null; then
-    message -error "Error: grep y/o sudo no están instalados o no se encuentran en el PATH."
-    exit 1
-fi
-
 # Pide la contraseña solo una vez al inicio
 sudo -v
 
@@ -46,6 +39,12 @@ CUSTOM_PATH=""
 EDITOR=""
 BROWSER=""
 WEATHER_KEY=""
+
+# Verifica que grep y sudo existan en el sistema
+if ! command -v grep &> /dev/null || ! command -v sudo &> /dev/null; then
+    message -error "Error: grep y/o sudo no están instalados o no se encuentran en el PATH."
+    exit 1
+fi
 
 # Procesa los argumentos con getopts y valida que no estén vacíos ni contengan otra opción
 while getopts "p:e:b:w:" opt; do
