clasificacion de colors scripts en el directorio local/ascii

diff --git a/local/bin/download-fonts b/local/bin/download-fonts
--- a/local/bin/download-fonts
+++ b/local/bin/download-fonts
@@ -31,12 +31,27 @@ function message() {
         "-title")       color="\033[0;37m\033[1m";      signal="[$]"; shift; echo -e "\n${color}${signal} $*${RESETC}";;
         "-subtitle")    color="\033[0;35m\033[1m";      signal="[*]"; shift; echo -e "\n${color}${signal} $*${RESETC}";;
         "-approval")    color="\033[38;5;51m\033[1m";   signal="[?]"; shift; echo -e "\n${color}${signal} $*${RESETC}";;
+        "-cancel")      color="\033[0;34m\033[1m";      signal="[!]"; shift; echo -e "\n${color}${signal} $*${RESETC}";;
         "-success")     color="\033[0;32m\033[1m";      signal="[+]"; shift; echo -e "\t${color}${signal} $*${RESETC}";;
         "-warning")     color="\033[0;33m\033[1m";      signal="[&]"; shift; echo -e "\t${color}${signal} $*${RESETC}";;
         "-error")       color="\033[0;31m\033[1m";      signal="[-]"; shift; echo -e "\t${color}${signal} $*${RESETC}";;
-        "-cancel")      color="\033[0;34m\033[1m";      signal="[!]"; shift; echo -e "\n${color}${signal} $*${RESETC}";;
         *)              color="$RESETC";                signal=""; shift; echo -e "${color}${signal} $*${RESETC}";;
     esac
+}
+
+trap ctrl_c INT
+function ctrl_c() {
+    message -cancel "Exiting...\n"
+    exit 1
+}
+
+function check_execution() {
+    if [ $1 != 0 ] && [ $1 != 130 ]; then
+        message -error "Error: $2"
+    else
+        message -success "Successful: $3"
+    fi
+    sleep 0.5
 }
 
 function is_valid_font() {
@@ -49,44 +64,48 @@ function is_valid_font() {
     return 1
 }
 
+#  ███╗   ███╗ █████╗ ██╗███╗   ██╗
+#  ████╗ ████║██╔══██╗██║████╗  ██║
+#  ██╔████╔██║███████║██║██╔██╗ ██║
+#  ██║╚██╔╝██║██╔══██║██║██║╚██╗██║
+#  ██║ ╚═╝ ██║██║  ██║██║██║ ╚████║
+#  ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝
+
 if [ $# -eq 0 ]; then
-    message -error "Error: At least one font must be provided as a parameter."
+    message -cancel "Error: At least one font must be provided as a parameter."
     exit 1
 fi
 
+set -e
 sudo -v
-DIR_TMP="/tmp/fonts_tmp"
+
+DIR_TMP=$(mktemp -d)
 DIR_FONTS="/usr/share/fonts"
+
 mkdir -p "$DIR_TMP"
+
+message -title "Downloading $font_name..."
+sleep 0.5
 
 for font_name in "$@"; do
     if is_valid_font "$font_name"; then
-        message -title "Downloading $font_name..."
+        message -subtitle "Downloading $font_name..."
         sleep 0.5
-        
         curl -L "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/${font_name}.tar.xz" -o "$DIR_TMP/${font_name}.tar.xz" >/dev/null 2>&1
         if [ $? -eq 0 ]; then
-            
             if [ -d "$DIR_FONTS/${font_name}" ]; then
                 sudo rm -rf "$DIR_FONTS/${font_name}"
             fi
-            
             sudo mkdir -p "$DIR_FONTS/${font_name}"
             sudo tar -xf "$DIR_TMP/${font_name}.tar.xz" -C "$DIR_FONTS/${font_name}" --wildcards "*.ttf" >/dev/null 2>&1
-            
-            if [ $? -eq 0 ]; then
-                message -success "Font $font_name copied to $DIR_FONTS successfully."
-            else
-                message -error "Error copying font $font_name to $DIR_FONTS."
-            fi
-        
+            check_execution $? "Error copying font $font_name to $DIR_FONTS." "Font $font_name copied to $DIR_FONTS successfully."
         else
             message -error "Error downloading font $font_name."
         fi
-    
     else
         message -error "Invalid font: $font_name"
     fi
+    sleep 0.5
 done
 
 
diff --git a/local/bin/packages-search b/local/bin/packages-search
--- a/local/bin/packages-search
+++ b/local/bin/packages-search
@@ -1,47 +1,120 @@
 #!/usr/bin/env bash
 
-DIR=$(pwd)
+function message() {
+    local signal color
+    local RESETC="\033[0m\e[0m"
+    case "$1" in
+        "-title")       color="\033[0;37m\033[1m";      signal="[$]"; shift; echo -e "\n${color}${signal} $*${RESETC}";;
+        "-subtitle")    color="\033[0;35m\033[1m";      signal="[*]"; shift; echo -e "\n${color}${signal} $*${RESETC}";;
+        "-approval")    color="\033[38;5;51m\033[1m";   signal="[?]"; shift; echo -e "\n${color}${signal} $*${RESETC}";;
+        "-cancel")      color="\033[0;34m\033[1m";      signal="[!]"; shift; echo -e "\n${color}${signal} $*${RESETC}";;
+        "-success")     color="\033[0;32m\033[1m";      signal="[+]"; shift; echo -e "\t${color}${signal} $*${RESETC}";;
+        "-warning")     color="\033[0;33m\033[1m";      signal="[&]"; shift; echo -e "\t${color}${signal} $*${RESETC}";;
+        "-error")       color="\033[0;31m\033[1m";      signal="[-]"; shift; echo -e "\t${color}${signal} $*${RESETC}";;
+        *)              color="$RESETC";                signal=""; shift; echo -e "${color}${signal} $*${RESETC}";;
+    esac
+}
+
+function usage() {
+    message -title "Usage: "
+    message -warning "Flags         Example"
+    message -success "-f [file]     $0 -f packages.txt"
+    message -success "[no-flag]     $0 <packages-1> <packages-2> <packages-N>"
+    echo ""
+    exit 1
+}
+
+trap ctrl_c INT
+function ctrl_c() {
+    message -cancel "Exiting...\n"
+    exit 1
+}
+
+function check_execution() {
+    if [ $1 != 0 ] && [ $1 != 130 ]; then
+        message -error "Error: $2"
+    else
+        message -success "Successful: $3"
+    fi
+    sleep 0.5
+}
+
+#  ███╗   ███╗ █████╗ ██╗███╗   ██╗
+#  ████╗ ████║██╔══██╗██║████╗  ██║
+#  ██╔████╔██║███████║██║██╔██╗ ██║
+#  ██║╚██╔╝██║██╔══██║██║██║╚██╗██║
+#  ██║ ╚═╝ ██║██║  ██║██║██║ ╚████║
+#  ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝
+
 DISTRO=$(grep -i '^ID=' /etc/os-release | cut -d= -f2 | tr -d '"' | tr '[:upper:]' '[:lower:]')
+TEXT=""
+FILE=""
+CHECK_CMD=""
+AVAILABLE_CMD=""
+
+OPTERR=0
+while getopts ":f:" opt; do
+    case ${opt} in
+        f)
+            FILE="$OPTARG"
+            if [[ -z "$FILE" ]]; then
+                message -error "La opción -f requiere un valor válido."
+                exit 1
+            fi
+            ;;
+        \?)
+            usage
+            ;;
+    esac
+done
+
+shift $((OPTIND - 1))
+
+if [ -z "$FILE" ] && [ $# -eq 0 ]; then
+    message -error "Se requiere al menos un argumento o la opción '-f' con un valor."
+    usage
+fi
+
+if [ -z "$FILE" ] && [ $# -gt 0 ]; then
+    # echo "Usando argumentos adicionales: $@"
+    PACKAGES=("$@")
+fi
+
+if [ -n "$FILE" ]; then
+    echo "Archivo recibido: $FILE"
+    if [[ ! -f "$FILE" ]]; then
+        message -error "El archivo no existe: $FILE"
+        exit 1
+    fi
+    PACKAGES=$(grep -Ev '^#|^$' "$FILE")
+fi
 
 case "$DISTRO" in
     debian|ubuntu|kali|mint|parrot)
-        PACKAGES_FILE="$DIR/packages/debian/list-packages.txt"
         CHECK_CMD="dpkg -l | grep -qw"
         AVAILABLE_CMD="apt-cache show"
-        ;;
+    ;;
     arch|manjaro)
-        PACKAGES_FILE="$DIR/packages/arch/list-packages.txt"
-        CHECK_CMD="pacman -Qq"
+        CHECK_CMD="pacman -Qq | grep -w"
         AVAILABLE_CMD="pacman -Si"
-        ;;
+    ;;
     fedora|centos|rhel)
-        PACKAGES_FILE="$DIR/packages/fedora/list-packages.txt"
         CHECK_CMD="rpm -q"
         AVAILABLE_CMD="dnf info"
-        ;;
+    ;;
     *)
-        echo "[CANCEL] Unsupported distribution: $DISTRO"
+        message -cancel "Distribución no soportada: $DISTRO"
         exit 1
-        ;;
+    ;;
 esac
 
-if [[ ! -f "$PACKAGES_FILE" ]]; then
-    echo "[CANCEL] There is no file related to your distribution."
-    exit 1
-fi
-
-echo "File detected. Checking package statuses..."
-sleep 0.5
-
-grep -Ev '^#|^$' "$PACKAGES_FILE" | while IFS= read -r package; do
+for package in ${PACKAGES[@]}; do
+    # CHECK_CMD NO FUNCIONA (TEST CON UBUNTU)
     if $CHECK_CMD "$package" &>/dev/null; then
-        echo "[INSTALLED] $package"
-        # continue
+        message -success "[INSTALADO] $package"
     elif $AVAILABLE_CMD "$package" &>/dev/null; then
-        echo "[AVAILABLE] $package"
-        # continue
+        message -warning "[DISPONIBLE] $package"
     else
-        echo "[NOT AVAILABLE] $package"
-        # continue
+        message -error "[NO DISPONIBLE] $package"
     fi
 done
